export const AuthActions = {
  AUTH_SIGNUP: "AUTH_SIGNUP",
  AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  AUTH_SIGNUP_ERROR: "AUTH_SIGNUP_ERROR",
  AUTH_SIGNIN: "AUTH_SIGNIN",
  AUTH_SIGNIN_SUCCESS: "AUTH_SIGNIN_SUCCESS",
  AUTH_SIGNIN_ERROR: "AUTH_SIGNIN_ERROR",
};
