export const productActions = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
  LOAD_PRODUCTS_ERROR: "LOAD_PRODUCTS_ERROR",
  LOAD_SAVE_PRODUCT: "LOAD_SAVE_PRODUCT",
  LOAD_SAVE_PRODUCT_SUCCESS: "LOAD_SAVE_PRODUCT_SUCCESS",
  LOAD_SAVE_PRODUCT_ERROR: "LOAD_SAVE_PRODUCT_ERROR",
};
