export const productActions = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOAD_PRODUCTS_SUCCESS: "LOAD_PRODUCTS_SUCCESS",
  LOAD_PRODUCTS_ERROR: "LOAD_PRODUCTS_ERROR",

  LOAD_SAVE_PRODUCT: "LOAD_SAVE_PRODUCT",
  LOAD_SAVE_PRODUCT_SUCCESS: "LOAD_SAVE_PRODUCT_SUCCESS",
  LOAD_SAVE_PRODUCT_ERROR: "LOAD_SAVE_PRODUCT_ERROR",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_CART",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",
};
